# Generated by Django 4.1.7 on 2023-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_product_alter_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_holders_list',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
