# Generated by Django 4.1.7 on 2023-03-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_rename_medicine_product_holders_list_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_holders_list',
            old_name='product',
            new_name='medicine',
        ),
    ]
