# Generated by Django 4.1.7 on 2023-03-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_order_quantity_alter_product_holders_list_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Purchased_Products',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email.html',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='email.html',
            new_name='email',
        ),
    ]
